# Generated by Django 3.0.4 on 2020-03-25 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareCompanyAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_transaction_date', models.DateField(verbose_name='Share Date')),
                ('total_transaction_time', models.TimeField(verbose_name='share Time')),
                ('total_amount', models.FloatField(verbose_name='Total Amount Rs.')),
                ('total_quantity', models.IntegerField(verbose_name='Total Quantity')),
                ('total_num_of_transactions', models.IntegerField(verbose_name='Total Number of Transactions')),
            ],
        ),
        migrations.CreateModel(
            name='ShareCompanyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_full_name', models.CharField(max_length=256, unique=True, verbose_name='Full Name')),
                ('company_short_name', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Short Name')),
            ],
        ),
        migrations.CreateModel(
            name='ShareCompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_transaction_date', models.DateField(verbose_name='Share Date')),
                ('company_transaction_time', models.TimeField(verbose_name='share Time')),
                ('company_sn', models.IntegerField(verbose_name='Daily ID')),
                ('company_num_of_transaction', models.IntegerField(verbose_name='Total Number of Transaction')),
                ('company_max_price', models.FloatField(verbose_name='Company Max Price')),
                ('company_min_price', models.FloatField(verbose_name='Company Min Price')),
                ('company_closing_price', models.FloatField(verbose_name='Company Closing Price')),
                ('company_traded_shares', models.IntegerField(verbose_name='Company Traded Shares')),
                ('company_total_amount', models.FloatField(verbose_name='Company Total Transaction Amount')),
                ('company_previous_closing', models.FloatField(verbose_name='Company Closing Price')),
                ('company_difference', models.FloatField(verbose_name='Company Difference')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareManager.ShareCompanyName')),
            ],
        ),
    ]
