# Generated by Django 3.0.4 on 2020-03-30 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shareManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareManagerUserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_phone_number_1', models.CharField(max_length=15, verbose_name='Phone Number 1')),
                ('share_phone_number_2', models.CharField(max_length=15, verbose_name='Phone Number 2')),
                ('share_email_1', models.CharField(max_length=15, verbose_name='email 1')),
                ('share_email_2', models.CharField(max_length=15, verbose_name='email 2')),
                ('Share_address', models.CharField(max_length=512, verbose_name='Address')),
                ('Share_city', models.CharField(max_length=256, verbose_name='city')),
                ('Share_country', models.CharField(max_length=128, verbose_name='country')),
                ('share_profile_picture', models.ImageField(default='profilePicture/default.png', upload_to='profilePicture', verbose_name='Share Profile Picture')),
                ('share_dashboard_left_nav_show', models.BooleanField(default=True)),
                ('show_notification_popup', models.BooleanField(default=True)),
                ('show_email_popup', models.BooleanField(default=True)),
                ('keep_activity_log', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
