# Generated by Django 3.0.4 on 2020-03-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareManager', '0003_sharemanagerusersharevalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharemanagerusersharevalues',
            name='share_company_buy_or_sell',
            field=models.BooleanField(default=True),
        ),
    ]
