# Generated by Django 3.0.4 on 2020-03-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareManager', '0007_sharemanagerledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharemanagerusersharevalues',
            name='share_company_number_of_shares_bought',
            field=models.IntegerField(),
        ),
    ]
