# Generated by Django 3.0.4 on 2020-04-02 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareManager', '0008_auto_20200331_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharemanagerusersharevalues',
            name='bought_per_unit_price',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 13, 37, 38, 80763)),
        ),
    ]
