# Generated by Django 3.0.4 on 2020-04-02 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareManager', '0009_sharemanagerusersharevalues_bought_per_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharemanagerusersharevalues',
            old_name='share_company_buy_or_sell',
            new_name='share_company_buy',
        ),
        migrations.RemoveField(
            model_name='sharemanagerusersharevalues',
            name='bought_per_unit_price',
        ),
        migrations.AddField(
            model_name='sharemanagerusersharevalues',
            name='current_share_amount_ledger',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sharemanagerusersharevalues',
            name='current_share_count_ledger',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharemanagerusersharevalues',
            name='share_bought_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 14, 4, 35, 867422), verbose_name='Share Bought Date'),
        ),
        migrations.AlterField(
            model_name='sharemanagerusersharevalues',
            name='share_company_bought_per_unit_price',
            field=models.FloatField(verbose_name='Share Per Unit Price'),
        ),
        migrations.AlterField(
            model_name='sharemanagerusersharevalues',
            name='share_company_bought_total_price',
            field=models.FloatField(blank=True, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='sharemanagerusersharevalues',
            name='share_company_number_of_shares_bought',
            field=models.IntegerField(verbose_name='Number of share Bought'),
        ),
    ]
