# Generated by Django 3.0.4 on 2020-04-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareManager', '0010_auto_20200402_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharemanagerusersharevalues',
            name='share_bought_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Share Bought Date'),
        ),
    ]
