# Generated by Django 3.0.4 on 2020-04-02 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareManager', '0011_auto_20200402_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharemanagerusersharevalues',
            name='share_bought_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Share Bought Date'),
        ),
    ]
