# Generated by Django 3.0.4 on 2020-04-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareManager', '0012_auto_20200402_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShareManagerLedger',
        ),
    ]
