# Generated by Django 3.0.4 on 2020-05-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareManager', '0013_delete_sharemanagerledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharemanagerusersharevalues',
            name='share_company_name',
        ),
        migrations.RemoveField(
            model_name='sharemanagerusersharevalues',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShareManagerUserDetails',
        ),
        migrations.DeleteModel(
            name='ShareManagerUserShareValues',
        ),
    ]
