# Generated by Django 3.0.4 on 2020-05-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareManager', '0015_apikeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeys',
            name='key',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
